# Generated by Django 5.2.3 on 2025-06-21 08:14

import django.db.models.deletion
import logs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.CharField(
                        default=logs.models.generate_user_id,
                        editable=False,
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.CharField(max_length=10)),
                ("arrival", models.CharField(blank=True, max_length=10, null=True)),
                ("lunch_start", models.CharField(blank=True, max_length=10, null=True)),
                ("lunch_end", models.CharField(blank=True, max_length=10, null=True)),
                ("departure", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logs.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "date")},
            },
        ),
    ]
